.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bewcore_qt test_bewcore_qt
clean: FORCE
	$(MAKE) -C .. bewcore_qt_clean test_bewcore_qt_clean
check: FORCE
	$(MAKE) -C .. test_bewcore_qt_check
bewcore-qt bewcore-qt.exe: FORCE
	 $(MAKE) -C .. bewcore_qt
apk: FORCE
	$(MAKE) -C .. bewcore_qt_apk
